routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource("product", "ProductController")->except(["show"]);
Route::resource("customer", "CustomerController")->except(["show"]);
Route::resource("invoice", "InvoiceController")->except(["show"]);

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $fillable = ["name", "address", "phone", "email"];
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Customer;

class CustomerController extends Controller
{
    public function index() {
        $customers = Customer::orderBy("created_at", "DESC")->paginate(10);

        return view("customers.index", compact("customers"));
    }

    public function create() {
        return view("customers.create");
    }

    public function store(Request $request) {
        $this->validate($request, [
            'name' => 'required|string',
            'phone' => 'required|max:13',
            'address' => 'required|string',
            'email' => 'required|email|string|unique:customers,email'
        ]);

        Customer::create($request->except("_token"));
        
        return redirect(route("customer.index"))->with(["success" => "Pelanggan berhasil ditambahkan."]);
    }

    public function edit(Request $request, $id) {
        $customer = Customer::findOrFail($id);

        return view("customers.edit", compact("customer"));
    }

    public function update(Request $request, $id) {
        $this->validate($request, [
            'name' => 'required|string',
            'phone' => 'required|max:13',
            'address' => 'required|string',
            'email' => 'required|email|string|exists:customers,email'
        ]);

        $customer = Customer::findOrFail($id);

        $customer->update($request->except("_token"));
        
        return redirect(route("customer.index"))->with(["success" => "Pelanggan berhasil diubah."]);
    }

    public function destroy($id) {
        $customer = Customer::findOrFail($id);
        $customer->delete();

        return redirect(route("customer.index"))->with(["success" => "Pelanggan berhasil dihapus."]);
    }
}

resources/views/customers/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tambah Data Pelanggan</h3>
                </div>

                <div class="card-body">
                    <form action="{{ route('customer.store') }}" method="post">
                        @csrf

                        <div class="form-group">
                            <label for="name">Nama Lengkap</label>
                            <input type="text" name="name"
                                class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}"
                                placeholder="Masukkan nama lengkap">

                            <p class="text-danger">{{ $errors->first('name') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="name">Alamat</label>
                            <textarea name="address" cols="5" rows="5"
                                class="form-control {{ $errors->has('address') ? 'is-invalid' : '' }}"
                                placeholder="Masukkan alamat pelanggan"></textarea>

                            <p class="text-danger">{{ $errors->first('address') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="phone">Phone</label>
                            <input type="text" name="phone"
                                class="form-control {{ $errors->has('phone') ? 'is-invalid' : '' }}"
                                placeholder="Masukkan nomor telepon pelanggan">

                            <p class="text-danger">{{ $errors->first('phone') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="text" name="email"
                                class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}"
                                placeholder="Masukkan email pelanggan">

                            <p class="text-danger">{{ $errors->first('email') }}</p>
                        </div>

                        <div class="form-group float-right">
                            <button class="btn btn-danger btn-sm">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tambah Data Pelanggan</h3>
                </div>

                <div class="card-body">

                    <form action="{{ route('customer.update', $customer->id) }}" method="post">
                        @csrf
                        @method("PUT")

                        <div class="form-group">
                            <label for="name">Nama Lengkap</label>
                            <input type="text" name="name"
                                class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}"
                                value="{{ $customer->name }}" placeholder="Masukkan nama lengkap">

                            <p class="text-danger">{{ $errors->first('name') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="address">Alamat</label>
                            <textarea name="address" cols="5" rows="5"
                                class="form-control {{ $errors->has('address') ? 'is-invalid' : '' }}"
                                placeholder="Masukkan alamat pelanggan">{{ $customer->address }}</textarea>

                            <p class="text-danger">{{ $errors->first('address') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="phone">Phone</label>
                            <input type="text" name="phone"
                                class="form-control {{ $errors->has('phone') ? 'is-invalid':'' }}"
                                value="{{ $customer->phone }}" placeholder="Masukkan nomor telepon pelanggan">

                            <p class="text-danger">{{ $errors->first('phone') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="number">Email</label>
                            <input type="email" name="email"
                                class="form-control {{ $errors->has('email') ? 'is-invalid':'' }}"
                                value="{{ $customer->email }}" placeholder="Masukkan email pelanggan">

                            <p class="text-danger">{{ $errors->first('email') }}</p>
                        </div>

                        <div class="form-group float-right">
                            <button class="btn btn-danger btn-sm">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customers/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h3 class="card-title">Manajemen Data Pelanggan</h3>
                        </div>

                        <div class="col-md-6">
                            <a href="{{ route('customer.create') }}" class="btn btn-primary btn-sm float-right">Tambah
                                Data</a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                    @endif

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>Nama Lengkap</th>
                                <th>No Telp</th>
                                <th>Alamat</th>
                                <th>Email</th>
                                <th colspan="2">Aksi</th>
                            </tr>
                        </thead>

                        <tbody>
                            @forelse($customers as $customer)
                            <tr>
                                <td>{{ $customer->name }}</td>
                                <td>{{ $customer->phone }}</td>
                                <td>{{ Str::limit($customer->address, 50) }}</td>
                                <td><a href="mailto:{{ $customer->email }}">{{ $customer->email }}</a></td>
                                <td>
                                    <form action="{{ route('customer.destroy', $customer->id) }}" method="POST">
                                        @csrf
                                        @method("DELETE")

                                        <a href="{{ route('customer.edit', $customer->id) }}"
                                            class="btn btn-warning btn-sm">Edit</a>

                                        <button class="btn btn-danger btn-sm">Hapus</button>
                                    </form>
                                </td>

                                <td>
                                    <form action="{{ route('invoice.store') }}" method="post">
                                        @csrf

                                        <input type="hidden" name="customer_id" value="{{ $customer->id }}"
                                            class="form-control">
                                        <button class="btn btn-primary btn-sm">Buat Invoice</button>
                                    </form>
                                </td>
                            </tr>

                            @empty
                            <tr>
                                <td class="text-center" colspan="5">Tidak ada data</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>

                    <div class="float-right">
                        {{ $customers->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection