routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource("product", "ProductController")->except(["show"]);
Route::resource("customer", "CustomerController")->except(["show"]);
Route::resource("invoice", "InvoiceController")->except(["show"]);

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ["title", "description", "price", "stock"];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    public function index() {
        $products = Product::orderBy("created_at", "DESC")->get();

        return view("products.index", compact("products"));
    }

    public function create() {
        return view("products.create");
    }

    public function store(Request $request) {
        $validation = $this->validate($request, [
            "title" => "required|string|max:100",
            "description" => "required|string",
            "price" => "required|integer",
            "stock" => "required|integer",
        ]);

        Product::create($request->except("_token"));
        
        return redirect(route("product.index"))->with(["success" => "Produk berhasil ditambahkan."]);
    }

    public function edit($id) {
        $product = Product::findOrFail($id);

        return view("products.edit", compact("product"));
    }

    public function update(Request $request, $id) {
        $validation = $this->validate($request, [
            "title" => "required|string|max:100",
            "description" => "required|string",
            "price" => "required|integer",
            "stock" => "required|integer",
        ]);

        $product = Product::findOrFail($id);

        $product->update($request->except("_token"));

        return redirect(route("product.index"))->with(["success" => "Produk berhasil diubah."]);
    }

    public function destroy($id) {
        $product = Product::findOrFail($id);
        $product->delete();

        return redirect(route("product.index"))->with(["success" => "Produk berhasil dihapus."]);
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tambah Data Produk</h3>
                </div>
                <div class="card-body">
                    <form action="{{ route('product.store') }}" method="post">
                        @csrf

                        <div class="form-group">
                            <label for="title">Nama Produk</label>
                            <input type="text" name="title" class="form-control" placeholder="Masukkan nama produk">

                            @if ($errors->has('title'))
                            <span class="text-danger">{{ $errors->first('title') }}</span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="description">Deskripsi</label>
                            <textarea name="description" cols="10" rows="10" class="form-control"
                                placeholder="Masukkan deskripsi produk"></textarea>

                            @if ($errors->has('description'))
                            <span class="text-danger">{{ $errors->first('description') }}</span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="price">Harga</label>
                            <input type="number" name="price" class="form-control" placeholder="Masukkan harga produk">

                            @if ($errors->has('price'))
                            <span class="text-danger">{{ $errors->first('price') }}</span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="stock">Stok</label>
                            <input type="number" name="stock" class="form-control" placeholder="Masukkan stok produk">

                            @if ($errors->has('stock'))
                            <span class="text-danger">{{ $errors->first('stock') }}</span>
                            @endif
                        </div>

                        <div class="form-group float-right">
                            <button class="btn btn-danger btn-sm">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Edit Data Produk</h3>
                </div>
                <div class="card-body">
                    <form action="{{ route('product.update', $product->id) }}" method="post">
                        @csrf
                        @method('PUT')

                        <div class="form-group">
                            <label for="title">Nama Produk</label>
                            <input type="text" name="title" class="form-control" value="{{ $product->title }}"
                                placeholder="Masukkan nama produk">

                            @if ($errors->has('title'))
                            <span class="text-danger">{{ $errors->first('title') }}</span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="description">Deskripsi</label>
                            <textarea name="description" cols="10" rows="10" class="form-control"
                                placeholder="Masukkan deskripsi produk">{{ $product->description }}</textarea>

                            @if ($errors->has('description'))
                            <span class="text-danger">{{ $errors->first('description') }}</span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="price">Harga</label>
                            <input type="number" name="price" class="form-control" value="{{ $product->price }}"
                                placeholder="Masukkan harga produk">

                            @if ($errors->has('price'))
                            <span class="text-danger">{{ $errors->first('price') }}</span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="stock">Stok</label>
                            <input type="number" name="stock" class="form-control" value="{{ $product->stock }}"
                                placeholder="Masukkan stok produk">

                            @if ($errors->has('stock'))
                            <span class="text-danger">{{ $errors->first('stock') }}</span>
                            @endif
                        </div>

                        <div class="form-group float-right">
                            <button class="btn btn-primary btn-sm">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h3 class="card-title">Manajemen Produk</h3>
                        </div>

                        <div class="col-md-6">
                            <a href="{{ route('product.create') }}" class="btn btn-primary btn-sm float-right">Tambah
                                Data</a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                    @endif

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>Nama Produk</th>
                                <th>Deskripsi</th>
                                <th>Harga</th>
                                <th>Stok</th>
                                <th>Tanggal</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>

                        <tbody>
                            @forelse($products as $product)
                            <tr>
                                <!-- MENAMPILKAN VALUE DARI TITLE -->
                                <td>{{ $product->title }}</td>
                                <td>{{ Str::limit($product->description, 50) }}</td>
                                <td>Rp {{ number_format($product->price) }}</td>
                                <td>{{ $product->stock }}</td>
                                <td>{{ $product->created_at->format('d-m-Y') }}</td>
                                <!-- TOMBOL DELETE MENGGUNAKAN METHOD DELETE DALAM ROUTING SEHINGGA KITA MEMASUKKAN TOMBOL TERSEBUT KEDALAM TAG <FORM></FORM> -->
                                <td>
                                    <form action="{{ route('product.destroy', $product->id) }}" method="POST">
                                        @csrf
                                        @method("DELETE")

                                        <a href="{{ route('product.edit', $product->id) }}"
                                            class="btn btn-warning btn-sm">Edit</a>

                                        <button class="btn btn-danger btn-sm">Hapus</button>
                                    </form>
                                </td>
                            </tr>

                            @empty
                            <tr>
                                <td class="text-center" colspan="6">Tidak ada data</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection